tasks:
  - init: ./mvnw install spring-boot:start spring-boot:stop

    command: ./mvnw
ports:
  - port: 8080
    onOpen: open-preview
github:
  prebuilds:
    # enable prebuilds for all branches in this repo
    branches: true 
